### ISSUE TITLE
Segmentation fault in compound statement on Genode

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-components#1]
When running the block correctness test on Genode I run into a segmentation fault (on base-linux) in the ringbuffer that doesn't use any platform interfaces. After som investigation I noticed that
```Ada
R.Data  := (others => (Block.Id'Last, False, Null_Buffer));
```
caused the segmentation fault. All inputs come from pure Ada and do not have any platform interaction. Also no C++ runtime or interface code was called in this statement.

Changing this statement to
```Ada
for I in R.Data'Range loop                                                                                        
   R.Data (I).Block_Id := Block.Id'Last;                                                                          
   R.Data (I).Set      := False;                                                                                  
   R.Data (I).Data     := Null_Buffer;                                                                            
end loop;
```
solved the issue. I suspect that some compiler generated code is used that either the runtime or the interface library are not configured for. On Linux the same code works without issues. We should check where we might have to enforce static initialization or forbid those statements (at least for larger loops). A [`pragma Restrictions (No_Implicit_Loops)`](https://docs.adacore.com/gnat_rm-docs/html/gnat_rm/gnat_rm/standard_and_implementation_defined_restrictions.html#no-implicit-loops) might prevent such constructs although some constants might not be able to be initialized anymore.

**Comment by senier** [comment]
Code has been refactored, problem gone.
