### ISSUE TITLE
GPT Partitioner

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-components#2]
As a real world use case for the [Gneiss](../../../Componolit/gneiss) we should build a partition manager for GPT partitions. This is a showcase to see if our interface can cope with real world work loads. It also addresses the issue on how labels should be handled in regard to how a server can route incoming requests.

**Comment by jklmnn** [comment]
Is this still up to date or do we want to close it?

**Comment by senier** [comment]
Outdated.
