### ISSUE TITLE
Implement block cache

### ISSUE THREAD

**Issue by senier** [Componolit/ada-components#4]
Requests are split into blocks. For every write request, blocks are put into the cache and written to the backend device. Every read request, is looked up in the cache. For a miss, the block is read from the backend device and put into the cache. For a hit, the request is serviced from the cache.

Cache entries are evicted on a LRU basis.

**Comment by jklmnn** [comment]
Is this still active or do we want to close it?

**Comment by senier** [comment]
No, we can open a new issue when we need such a component.
